vim.keymap.set('i', 'jk', '<Esc>')
vim.keymap.set("t", "jk", "<C-\\><C-n>")
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
vim.keymap.set("n", "<M-j>", ":cnext<CR>", { silent = true })
vim.keymap.set("n", "<M-k>", ":cprev<CR>", { silent = true })
vim.keymap.set("n", "<M-h>", ":tabp<CR>", { silent = true })
vim.keymap.set("n", "<M-l>", ":tabn<CR>", { silent = true })
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "<leader>*", function()
	local commit_msg = vim.fn.input("Enter commit message: ")
	vim.cmd("git add %;git commit -m " .. commit_msg .. " ; git push work master")
end)
